
### Create Category (POST)
POST http://localhost:3000/api/categories/create
Content-Type: application/json
X-ACCESS-TOKEN: {token}

{
  "name": "Minuman"
}

### Get All Categories (GET)
GET http://localhost:3000/api/categories
X-ACCESS-TOKEN: {token}

### Get Category by ID (GET)
GET http://localhost:3000/api/categories/1
X-ACCESS-TOKEN: {token}

### Update Category (PUT)
PUT http://localhost:3000/api/categories/1
Content-Type: application/json
X-ACCESS-TOKEN: {token}

{
  "name": "Makanan"
}

### Delete Category (DELETE)
DELETE http://localhost:3000/api/categories/1
X-ACCESS-TOKEN: {token}