### Register User (POST)
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email" : "admin@admin.com",
  "password" : "admin",
  "name" : "Admin"
}

### Login User (POST)
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### Get Current User (GET) - Protected
GET http://localhost:3000/api/users/me
X-ACCESS-TOKEN: {token}

### Logout User (DELETE) - Protected
DELETE http://localhost:3000/api/users/me
X-ACCESS-TOKEN: {token}
